const String login = "Login";
const String home = "HomePage";
const String movie_detail = "MovieDetail";
const String sign_up = "SignUp";
const String book_seats = "BookSeats";
const String tickets = "Tickets";
const String checkout = "Checkout";
const String history ="History";
const String ticket_detail ="TicketDetail";
